// Do NOT make any changes to this file!

import uuidAPIKey from "uuid-apikey";

// converts a uuid to a string resembling an API Key
//  id must be valid uuid
export function getKey(id) {
  return uuidAPIKey.toAPIKey(id, { noDashes: true });
}

// converts an API Key string to a uuid
//  key must be one that was generated by uuid-apikey
export function getId(key) {
  return uuidAPIKey.toUUID(key);
}
